-- V1__initial_schema.sql
-- Full schema for BeyondSelf Digital Twin backend.
-- Uses IF NOT EXISTS throughout so this migration is safe on existing databases.
-- FK constraints are added via DO blocks so they are also idempotent.
-- Tables are ordered by dependency: referenced tables are always created first.

-- ── 1. users ──────────────────────────────────────────────────────────────────
-- Root table — every other table references users.id.
CREATE TABLE IF NOT EXISTS users (
    id            varchar(36)  NOT NULL,
    email         varchar(255) NOT NULL,
    password_hash varchar(255),
    name          varchar(255),
    created_at    timestamp(6),
    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ── 2. import_history ─────────────────────────────────────────────────────────
-- Created BEFORE the record tables because career/finance/health records have
-- an import_id FK that references this table.
CREATE TABLE IF NOT EXISTS import_history (
    id                bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id           varchar(255)  NOT NULL,
    original_filename varchar(255)  NOT NULL,
    storage_path      varchar(255)  NOT NULL,
    mime_type         varchar(255)  NOT NULL,
    file_type         varchar(255),
    detected_domain   varchar(255),
    source            varchar(255),
    record_count      integer       NOT NULL DEFAULT 0,
    valid_count       integer       NOT NULL DEFAULT 0,
    invalid_count     integer       NOT NULL DEFAULT 0,
    status            varchar(255),
    error_message     varchar(255),
    column_headers    varchar(4000),
    sample_data       text,
    uploaded_at       timestamp(6),
    parsed_at         timestamp(6),
    CONSTRAINT pk_import_history PRIMARY KEY (id)
);

-- ── 3. health_records ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS health_records (
    id              bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id         varchar(255) NOT NULL,
    record_date     date,
    sleep_hours     float(53),
    stress_level    integer,
    mood_score      integer,
    workout_minutes integer,
    water_glasses   integer,
    calories        integer,
    bmi             float(53),
    heart_rate      integer,
    steps           integer,
    source          varchar(255),
    import_id       bigint,
    created_at      timestamp(6),
    CONSTRAINT pk_health_records PRIMARY KEY (id)
);

-- ── 4. career_records ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS career_records (
    id             bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id        varchar(255) NOT NULL,
    activity_date  date,
    study_hours    float(53),
    coding_hours   float(53),
    dsa_problems   integer,
    skill_learned  varchar(255),
    github_commits integer,
    github_repos   integer,
    source         varchar(255),
    import_id      bigint,
    created_at     timestamp(6),
    CONSTRAINT pk_career_records PRIMARY KEY (id)
);

-- Element-collection tables for CareerRecord (created right after the parent).
CREATE TABLE IF NOT EXISTS career_record_languages (
    career_record_id bigint,
    language         varchar(255)
);

CREATE TABLE IF NOT EXISTS career_record_skills (
    career_record_id bigint,
    skill            varchar(200)
);

CREATE TABLE IF NOT EXISTS career_record_projects (
    career_record_id bigint,
    project_title    varchar(500)
);

-- ── 5. finance_records ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS finance_records (
    id               bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id          varchar(255)  NOT NULL,
    transaction_date date,
    amount           numeric(38,2),
    category         varchar(255),
    description      varchar(255),
    transaction_type varchar(255),
    merchant         varchar(255),
    is_impulse       boolean,
    source           varchar(255),
    import_id        bigint,
    created_at       timestamp(6),
    CONSTRAINT pk_finance_records PRIMARY KEY (id)
);

-- ── 6. goals ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS goals (
    id            bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id       varchar(255)  NOT NULL,
    title         varchar(255)  NOT NULL,
    description   varchar(1000),
    domain        varchar(255),
    target_value  float(53),
    current_value float(53),
    unit          varchar(255),
    deadline      date,
    status        varchar(255),
    priority      varchar(255),
    milestones    varchar(2000),
    created_at    timestamp(6),
    updated_at    timestamp(6),
    CONSTRAINT pk_goals PRIMARY KEY (id)
);

-- ── 7. user_stats ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_stats (
    user_id               varchar(255) NOT NULL,
    xp                    integer      NOT NULL DEFAULT 0,
    level                 integer      NOT NULL DEFAULT 1,
    current_streak        integer      NOT NULL DEFAULT 0,
    longest_streak        integer      NOT NULL DEFAULT 0,
    last_activity_date    date,
    total_health_logs     integer      NOT NULL DEFAULT 0,
    total_finance_logs    integer      NOT NULL DEFAULT 0,
    total_career_logs     integer      NOT NULL DEFAULT 0,
    total_goals_completed integer      NOT NULL DEFAULT 0,
    created_at            timestamp(6),
    updated_at            timestamp(6),
    CONSTRAINT pk_user_stats PRIMARY KEY (user_id)
);

-- ── 8. user_badges ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_badges (
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     varchar(255) NOT NULL,
    badge_id    varchar(255) NOT NULL,
    badge_name  varchar(255),
    description varchar(255),
    domain      varchar(255),
    icon        varchar(255),
    earned_at   timestamp(6),
    CONSTRAINT pk_user_badges PRIMARY KEY (id)
);

-- ── 9. study_sessions ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS study_sessions (
    id               bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id          varchar(255) NOT NULL,
    session_date     date         NOT NULL,
    duration_minutes integer      NOT NULL,
    topic            varchar(255) NOT NULL,
    category         varchar(255),
    focus_quality    integer      NOT NULL DEFAULT 0,
    mental_fatigue   integer      NOT NULL DEFAULT 0,
    environment      varchar(255),
    xp_earned        integer      NOT NULL DEFAULT 0,
    created_at       timestamp(6),
    CONSTRAINT pk_study_sessions PRIMARY KEY (id)
);

-- ── 10. transaction_records ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS transaction_records (
    id               bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id          varchar(255) NOT NULL,
    amount           float(53)    NOT NULL,
    merchant         varchar(255),
    category         varchar(255),
    bank             varchar(255),
    transaction_type varchar(255),
    payment_mode     varchar(255),
    raw_message      text,
    source           varchar(255),
    parsed_at        timestamp(6) NOT NULL,
    CONSTRAINT pk_transaction_records PRIMARY KEY (id)
);

-- ── 11. fitbit_tokens ─────────────────────────────────────────────────────────
-- Persists Google Fit / Fitbit OAuth tokens across backend restarts.
-- user_id is the PK (one row per app user, upserted on every token refresh).
CREATE TABLE IF NOT EXISTS fitbit_tokens (
    user_id        varchar(255) NOT NULL,
    access_token   text         NOT NULL,
    refresh_token  text,
    google_user_id varchar(255),
    updated_at     timestamp(6),
    CONSTRAINT pk_fitbit_tokens PRIMARY KEY (user_id)
);

-- ── 12. Indexes ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_tx_user     ON transaction_records (user_id);
CREATE INDEX IF NOT EXISTS idx_tx_category ON transaction_records (category);

-- ── 12. Foreign key constraints ───────────────────────────────────────────────
-- Each block checks pg_constraint by name before adding, so re-running this
-- migration on an existing database never raises a "constraint already exists"
-- error — regardless of whether the constraint was previously unnamed.

-- Clean up orphaned records to prevent foreign key constraint violations on startup
DELETE FROM health_records WHERE user_id NOT IN (SELECT id FROM users);
UPDATE health_records SET import_id = NULL WHERE import_id IS NOT NULL AND import_id NOT IN (SELECT id FROM import_history);

DELETE FROM career_records WHERE user_id NOT IN (SELECT id FROM users);
UPDATE career_records SET import_id = NULL WHERE import_id IS NOT NULL AND import_id NOT IN (SELECT id FROM import_history);

DELETE FROM career_record_languages WHERE career_record_id NOT IN (SELECT id FROM career_records);
DELETE FROM career_record_skills WHERE career_record_id NOT IN (SELECT id FROM career_records);
DELETE FROM career_record_projects WHERE career_record_id NOT IN (SELECT id FROM career_records);

DELETE FROM finance_records WHERE user_id NOT IN (SELECT id FROM users);
UPDATE finance_records SET import_id = NULL WHERE import_id IS NOT NULL AND import_id NOT IN (SELECT id FROM import_history);

DELETE FROM goals             WHERE user_id NOT IN (SELECT id FROM users);
DELETE FROM user_stats        WHERE user_id NOT IN (SELECT id FROM users);
DELETE FROM user_badges       WHERE user_id NOT IN (SELECT id FROM users);
DELETE FROM study_sessions    WHERE user_id NOT IN (SELECT id FROM users);
DELETE FROM transaction_records WHERE user_id NOT IN (SELECT id FROM users);
DELETE FROM fitbit_tokens     WHERE user_id NOT IN (SELECT id FROM users);

-- health_records → users
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_health_records_user_id') THEN
    ALTER TABLE health_records
      ADD CONSTRAINT fk_health_records_user_id
      FOREIGN KEY (user_id) REFERENCES users (id);
  END IF;
END $$;

-- health_records → import_history
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_health_records_import_id') THEN
    ALTER TABLE health_records
      ADD CONSTRAINT fk_health_records_import_id
      FOREIGN KEY (import_id) REFERENCES import_history (id);
  END IF;
END $$;

-- career_records → users
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_career_records_user_id') THEN
    ALTER TABLE career_records
      ADD CONSTRAINT fk_career_records_user_id
      FOREIGN KEY (user_id) REFERENCES users (id);
  END IF;
END $$;

-- career_records → import_history
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_career_records_import_id') THEN
    ALTER TABLE career_records
      ADD CONSTRAINT fk_career_records_import_id
      FOREIGN KEY (import_id) REFERENCES import_history (id);
  END IF;
END $$;

-- finance_records → users
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_finance_records_user_id') THEN
    ALTER TABLE finance_records
      ADD CONSTRAINT fk_finance_records_user_id
      FOREIGN KEY (user_id) REFERENCES users (id);
  END IF;
END $$;

-- finance_records → import_history
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_finance_records_import_id') THEN
    ALTER TABLE finance_records
      ADD CONSTRAINT fk_finance_records_import_id
      FOREIGN KEY (import_id) REFERENCES import_history (id);
  END IF;
END $$;

-- study_sessions → users
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_study_sessions_user_id') THEN
    ALTER TABLE study_sessions
      ADD CONSTRAINT fk_study_sessions_user_id
      FOREIGN KEY (user_id) REFERENCES users (id);
  END IF;
END $$;

-- transaction_records → users
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transaction_records_user_id') THEN
    ALTER TABLE transaction_records
      ADD CONSTRAINT fk_transaction_records_user_id
      FOREIGN KEY (user_id) REFERENCES users (id);
  END IF;
END $$;

-- career_record_languages → career_records
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_career_record_languages_record') THEN
    ALTER TABLE career_record_languages
      ADD CONSTRAINT fk_career_record_languages_record
      FOREIGN KEY (career_record_id) REFERENCES career_records (id);
  END IF;
END $$;

-- career_record_skills → career_records
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_career_record_skills_record') THEN
    ALTER TABLE career_record_skills
      ADD CONSTRAINT fk_career_record_skills_record
      FOREIGN KEY (career_record_id) REFERENCES career_records (id);
  END IF;
END $$;

-- career_record_projects → career_records
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_career_record_projects_record') THEN
    ALTER TABLE career_record_projects
      ADD CONSTRAINT fk_career_record_projects_record
      FOREIGN KEY (career_record_id) REFERENCES career_records (id);
  END IF;
END $$;

-- fitbit_tokens → users
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fitbit_tokens_user_id') THEN
    ALTER TABLE fitbit_tokens
      ADD CONSTRAINT fk_fitbit_tokens_user_id
      FOREIGN KEY (user_id) REFERENCES users (id);
  END IF;
END $$;
