-- V2__sustainability.sql
-- Migration schema for Sustainability settings and Eco-Actions

-- ── 12. sustainability_settings ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sustainability_settings (
    user_id       varchar(36)  NOT NULL,
    sync_enabled  boolean      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_sustainability_settings PRIMARY KEY (user_id)
);

-- ── 13. eco_actions ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS eco_actions (
    id            bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id       varchar(255) NOT NULL,
    action_name   varchar(255) NOT NULL,
    carbon_saved  double precision NOT NULL,
    logged_at     timestamp(6) NOT NULL,
    CONSTRAINT pk_eco_actions PRIMARY KEY (id)
);

-- Add foreign keys via DO block for idempotent execution
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sustainability_settings_user_id') THEN
    ALTER TABLE sustainability_settings
      ADD CONSTRAINT fk_sustainability_settings_user_id
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_eco_actions_user_id') THEN
    ALTER TABLE eco_actions
      ADD CONSTRAINT fk_eco_actions_user_id
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
  END IF;
END $$;
