package com.digitaltwin.backend.util;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ResponseStatusException;

import java.util.Base64;

@Component
public class AuthUtil {

    private final JwtUtil jwtUtil;
    private static final ObjectMapper mapper = new ObjectMapper();

    public AuthUtil(JwtUtil jwtUtil) {
        this.jwtUtil = jwtUtil;
    }

    public String getUserIdFromToken(String authHeader) {
        if (authHeader == null || !authHeader.startsWith("Bearer ")) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Missing or invalid authorization token");
        }
        String token = authHeader.substring(7);

        // Legacy demo-mode tokens generated by the frontend
        if (token.startsWith("dt_jwt_")) {
            return parseLegacyToken(token);
        }

        // Real JWT issued by the backend
        return jwtUtil.getUserIdFromToken(token);
    }

    private String parseLegacyToken(String token) {
        try {
            String base64Payload = token.substring("dt_jwt_".length());
            String jsonPayload = new String(Base64.getDecoder().decode(base64Payload));
            JsonNode payload = mapper.readTree(jsonPayload);
            long exp = payload.get("exp").asLong();
            if (System.currentTimeMillis() > exp) {
                throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Token expired");
            }
            return payload.get("id").asText();
        } catch (ResponseStatusException e) {
            throw e;
        } catch (Exception e) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Invalid token format");
        }
    }
}
